apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          limits:
            cpu: 100m
      - name: metrics
        resources:
          limits:
            cpu: 100m
      - name: zipkin
        resources:
          limits:
            cpu: 100m
