apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  template:
    spec:
      containers:
        - name: app
          env:
          - name: SALES_DB_USER
            valueFrom:
              secretKeyRef:
                name: sales-api
                key: user
          - name: SALES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sales-api
                key: pass
          - name: SALES_DB_NAME
            valueFrom:
              secretKeyRef:
                name: sales-api
                key: db
          - name: SALES_DB_HOST
            valueFrom:
              secretKeyRef:
                name: sales-api
                key: db_host
