creation_rules:
  - path_regex: .*/staging/.*
    encrypted-regex: ^(data|stringData)$
#    gcp_kms: >-
#      projects/stackwise-starter-kit/locations/global/keyRings/gke-argocd/cryptoKeys/gke
    age: >-
      age1w826f40md3jtgcj62y6jhlyf6v0vpfh5h20e5p6cxq7rfwge7pqstwf3zc
  - path_regex: .*/production/.*
    encrypted-regex: ^(data|stringData)$
    age: >-
      age1w826f40md3jtgcj62y6jhlyf6v0vpfh5h20e5p6cxq7rfwge7pqstwf3zc
  - path_regex: \.enc\.env-db$
    age: >-
      age1w826f40md3jtgcj62y6jhlyf6v0vpfh5h20e5p6cxq7rfwge7pqstwf3zc
#     age1w826f40md3jtgcj62y6jhlyf6v0vpfh5h20e5p6cxq7rfwge7pqstwf3zc,
#     its currently not possible to add more than one recipient.
